export const testValues = {
    nullValue: null,
    undefinedValue: undefined,
    falseValue: false,
    trueValue: true,
    emptyString: '',
    nonemptyString: 'a',
    intString: '3',
    floatString: '1.25',
    emptyArray: [],
    nonemptyArray: [''],
    object: {},
    negativeOne: -1,
    zero: 0,
    one: 1,
};
